server:
  port: 8084
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: conveyor_route
          uri: http://localhost:8080/
          predicates:
            - Path=/conveyor/**
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false


